services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: echo_vuln
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo_pass_change_me
    ports:
      - "5432:5432"
    volumes:
      - echo_vuln_pg:/var/lib/postgresql/data

volumes:
  echo_vuln_pg:
